kind: VerticalPodAutoscaler
apiVersion: autoscaling.k8s.io/v1
metadata:
  name: frontend-vpa
  namespace: asphones
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend
  updatePolicy:
    updateMode: "Auto"
  # resourcePolicy:
  #   containerPolicies:
  #     - containerName: frontend
  #       minAllowed:
  #         cpu: "100m"
  #         memory: "128Mi"
  #       maxAllowed:
  #         cpu: "500m"
  #         memory: "256Mi"
