kind: Role 
apiVersion: rbac.authorization.k8s.io/v1
metadata: 
  name: asphones-manager
  namespace: asphones
rules: 
  - apiGroups: ["","apps", "extensions"]
    resources: ["pods", "deployments", "replicasets", "services", "configmaps", "secrets", "horizontalpodautoscalers", "ingresses"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
   
